import type { Metadata } from 'next'
import GlobalNav from "../components/global-nav"

export const metadata: Metadata = {
  title: 'React Gates',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GlobalNav />
        {children}
      </body>
    </html>
  )
}
