import type { Metadata } from 'next'
import {GlobalNav} from "../components/global-nav"
import "./globals.css"
import tutorialData from "../content/tutorials/tutorialcontent.json"

export const metadata: Metadata = {
  title: 'React Gates',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GlobalNav tutorialData={tutorialData.tutorials}/>
        {children}
      </body>
    </html>
  )
}
